[package]
name = "base58m"
description = "base64-like binary with support for encoding/decoding Monero base58 strings."
keywords = ["binary", "monero", "base58", "base58-check"]
version = "0.1.0"
authors = ["h4sh3d <h4sh3d@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/monero-rs/base58m-rs"
repository = "https://github.com/monero-rs/base58m-rs"
readme = "README.md"

include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

edition = "2018"

[dependencies]
clap = "2.33.0"
base58-monero = "0.2.0"
tokio = { version = "0.2", features = ["fs", "macros", "io-std", "io-util"] }
futures-util = "0.3.1"
async-stream = { version = "0.2.0" }

[badges]
travis-ci = { repository = "monero-rs/base58m-rs", branch = "master" }
