name: "Create release"

on:
  pull_request:
    types:
      - closed

jobs:
  create_release:
    name: Create from merged release branch
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    uses: monero-rs/workflows/.github/workflows/create-release.yml@0ed0d39dddf858a1c4396611f1d3e45111b7d320
    secrets:
      token: ${{ secrets.H4SH3D_PERSONAL_ACCESS_TOKEN }}
