name: "Release to crates.io"

on:
  release:
    types: [created]

jobs:
  release:
    name: "Publish the new release to crates.io"
    uses: monero-rs/workflows/.github/workflows/release-to-crates-io.yml@0ed0d39dddf858a1c4396611f1d3e45111b7d320
    secrets:
      cratesio_token: ${{ secrets.H4SH3D_CARGO_REGISTRY_TOKEN }}
